In [1]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [8]:
# code here
np.random.seed(42)
a = np.random.randint(0,101, size=(3,4))
a


array([[51, 92, 14, 71],
       [60, 20, 82, 86],
       [74, 74, 87, 99]])

In [48]:
arr = np.array([[92, 90, 74],
    [ 6, 63, 93],
    [15, 93, 96],
    [70, 60, 48]])
arr

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [12]:
# 1
np.sort(arr)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [14]:
# 2 based on second col
arr[arr[:, 1].argsort()]


array([[70, 60, 48],
       [ 6, 63, 93],
       [92, 90, 74],
       [15, 93, 96]])

In [35]:
# 3 based on max value in each row
arr[np.max(arr, axis=1).argsort()[::-1]]

array([[15, 93, 96],
       [ 6, 63, 93],
       [92, 90, 74],
       [70, 60, 48]])

In [52]:
# 4 sort based on element value
rr = np.sort(arr.flatten()).reshape(3, 4)
rr

array([[ 6, 15, 48, 60],
       [63, 70, 74, 90],
       [92, 93, 93, 96]])

###`Q-5:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [59]:
# code here
# 5 add col
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
extra_subject = np.array([[41], [87], [72], [36], [92]])

new = np.hstack((marks,extra_subject))
new

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [60]:
# 6 add 2 new students marks
rec1 = np.array([[77, 83, 98, 95, 89]])
rec2 = np.array([[92, 71, 52, 61, 53]])
new1 = np.vstack((new, rec1, rec2))
new1

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [65]:
# 7 add extra col with sum of all marks
sum_ = np.sum(new1, axis=1)
new2 = np.column_stack((new1, sum_))
new2

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [68]:
# 8 Sort the array in non-ascending order based on the total marks column and show top 2 rows
sort_ar = new2[new2[:, -1].argsort()[::-1]]
sort_ar[:2]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

###`Q-9:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [70]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
#9 row wise
np.unique(arr, axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [74]:
#10 col wise
np.unique(arr.T, axis=0).T

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-11:` Flip given 2-D array along both axes at the same time.

In [75]:
# code here
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
np.flip(a)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

### `Q-12:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [78]:
# code here
a = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
np.where(a>6)[0]     #rows indices 2 in 1st row, 2 in 3rd row

array([1, 1, 3, 3], dtype=int64)

### `Q-13:` How to convert an array of arrays into a flat 1d array?


In [79]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [ ]:
# Use np.ravel() for a flattened view.  multidims in 1D
# Use np.flatten() for a copy.
# Use reshape(-1) to change the shape.
# Use np.concatenate() for combining an array of arrays.
# Use list comprehension for lists.

In [83]:
# code here                               
np.concatenate((arr1,arr2,arr3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-14:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.


In [99]:
# code here
arr = np.array([1, 3, 5, 7, 2, 4, 6, 8, 0])

min_ele = arr.min()
max_ele = arr.max()

arr2 = arr[(arr != min_ele) & (arr != max_ele)]

min_ele, max_ele, arr2

(0, 8, array([1, 3, 5, 7, 2, 4, 6]))

### `Q-15:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [108]:
# code here
arr = np.array([40,50,97,105,764,353,244,900,9005,5444,400,242])
arr_clip = np.clip(arr,a_min=100, a_max=700)
print('limited arr: ', arr_clip)
# 16
arr1 = np.sort(arr_clip)
print('sorted arr: ', arr1)
# 17
arr2 = np.cumsum(arr1)
print('cumulative sum: ', arr2)

limited arr:  [100 100 100 105 700 353 244 700 700 700 400 242]
sorted arr:  [100 100 100 105 242 244 353 400 700 700 700 700]
cumulative sum:  [ 100  200  300  405  647  891 1244 1644 2344 3044 3744 4444]


### `Q-18:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [112]:
# code here
arr = np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [113]:
# 18 round off the elements upto 3 decimal places
np.round(arr, 3)

array([0.   , 0.053, 0.105, 0.158, 0.211, 0.263, 0.316, 0.368, 0.421,
       0.474, 0.526, 0.579, 0.632, 0.684, 0.737, 0.789, 0.842, 0.895,
       0.947, 1.   ])

In [114]:
# 19 0th percentile == minimum value of the array
np.percentile(arr, 0)

0.0

In [115]:
# 20 100th percentile == maximum value of the array
np.percentile(arr, 100)

1.0

In [116]:
# 21 find the difference betwen 51th percenile and 50th percentile values
diff = (np.percentile(arr, 51)) - (np.percentile(arr,50))
diff

0.009999999999999898